name: Build .NET

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Build version'
          required: true
          default: '0.0.0'
  workflow_call:
    inputs:
        version:
          description: 'Build version'
          required: true
          type: string
          
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore msovideo_srgb.sln

      - name: Publish Single-File
        run: dotnet publish msovideo_srgb/msovideo_srgb.csproj --configuration Release --runtime win-x64 --no-restore -p:PublishSingleFile=true -p:SelfContained=false -p:Version=${{ inputs.version }} -o publish

      - name: Prepare output folder
        run: |
          powershell -Command "New-Item -ItemType Directory -Force -Path output"
          powershell -Command "Copy-Item publish\*.exe output\"
          powershell -Command "Copy-Item LICENSE output\"
          powershell -Command "Copy-Item LICENSE-THIRD-PARTY output\"

      # Upload the output folder as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output/
