name: Release
run-name: Release v${{ github.event.inputs.version }} @ ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        pattern: '^[0-9]+\\.[0-9]+\\.[0-9]+$'
      notes:
        description: 'Release notes'
        required: true
      prerelease:
        description: 'Pre-release'
        required: true
        type: boolean
        default: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with: 
      version: ${{ github.event.inputs.version }}

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./artifact

      - name: Create ZIP from artifact
        run: powershell Compress-Archive -Path "artifact\*" -DestinationPath "msovideo_srgb.zip"

      - name: Prepare release notes 
        run: | 
          $notes = "${{ github.event.inputs.notes }}" -replace "\\n","`n" 
          Set-Content -Path RELEASE_NOTES.md -Value $notes

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body_path: RELEASE_NOTES.md
          prerelease: ${{ github.event.inputs.prerelease }}
          files: msovideo_srgb.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
